#!/usr/bin/env bash
# information about the holbertonschool file

NAMEF="Bestschool"
if [ -e "$NAMEF" ]
then
    echo "$NAMEF file exists"
    if [ -s "$NAMEF" ]
    then
	echo "Bestschool file is not empty"
    else
	echo "Bestschool file is empty"
    fi
    if [ -f "$NAMEF" ]
    then
	echo "Bestschool is a regular file"
    fi
else
    echo "Bestschool file does not exist"
fi
